#determinantes
#calculo de sistemas

In [1]:
import numpy as np

In [2]:
from numpy.linalg import det, inv

por que se o determinante for 0, nao tem solução para o sistema?

In [3]:
a = np.array([[1, 2 ,3],[4, 5, 6],[7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b = np.array([[14, 7, 75],[28, 4, 88], [10, 6, 89]])
b

array([[14,  7, 75],
       [28,  4, 88],
       [10,  6, 89]])

In [5]:
c = np.array([[3, 7, 9],[2, 1, 4],[-2, 4, -5]])
c

array([[ 3,  7,  9],
       [ 2,  1,  4],
       [-2,  4, -5]])

calculo de determinante

In [7]:
a1 = det(a)
print(a1)

0.0


In [8]:
a2 = inv(a)
print(a2)

LinAlgError: ignored

In [9]:
a3 = det(b)
print(a3)

-4091.9999999999955


In [10]:
a4 = inv(b)
print(a4)

[[ 0.04203324  0.04227761 -0.07722385]
 [ 0.39393939 -0.12121212 -0.21212121]
 [-0.03128055  0.00342131  0.0342131 ]]


In [11]:
d = np.array([[2,4,6],[8,10,12],[14,16,18]])
d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [13]:
a5 = det(d)
a5

0.0

In [14]:
e = np.array([[2,4,8],[16,32,64],[128,256,512]])
a6 = det(e)
a6

0.0

In [15]:
b1 = b.dot(a4)
b1

array([[ 1.00000000e+00, -1.05384451e-16, -2.15105711e-16],
       [-5.55111512e-17,  1.00000000e+00,  5.55111512e-17],
       [ 3.67761377e-16, -6.28837260e-17,  1.00000000e+00]])

In [16]:
invB = inv(a4)
invB


array([[14.,  7., 75.],
       [28.,  4., 88.],
       [10.,  6., 89.]])

In [17]:
mult1 = inv(b.dot(c))
mult1

array([[ 0.64616265, -0.22997282, -0.31192332],
       [ 0.02629759, -0.00630618, -0.01428129],
       [-0.23117087,  0.08625992,  0.10650168]])

In [18]:
mult2 = inv(b).dot(inv(c))
mult2

array([[-0.03830198,  0.12485397,  0.04638438],
       [-0.2594235 ,  0.80783444,  0.22172949],
       [ 0.0245333 , -0.07561452, -0.02317431]])