In [ ]:
import numpy as np

In [ ]:
A = np.matrix('2.0,2.0,6.0;3.0,1.0,1.0;3.0,8.0,4.0')
print(A)

[[2. 2. 6.]
 [3. 1. 1.]
 [3. 8. 4.]]


In [ ]:
X = np.identity(3)
print(X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
A[0,:] = 1/2*A[0,:]
print(A)

[[1. 1. 3.]
 [3. 1. 1.]
 [3. 8. 4.]]


In [ ]:
X[0,:] = 1/2*X[0,:]
print(X)

[[0.5 0.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]]


In [ ]:
A[1,:] = 3*A[0,:] - A[1,:]
print(A)

[[1. 1. 3.]
 [0. 2. 8.]
 [3. 8. 4.]]


In [ ]:
X[1,:] = 3*X[0,:] - A[1,:]
print(X)

[[ 0.5  0.   0. ]
 [ 1.5 -2.  -8. ]
 [ 0.   0.   1. ]]


In [ ]:
A[2,:] = 3*A[0,:] - A[2,:]
print(A)

[[ 1.  1.  3.]
 [ 0.  2.  8.]
 [ 0. -5.  5.]]


In [ ]:
X[2,:] = 3*X[0,:] - X[2,:]
print(X)

[[ 0.5  0.   0. ]
 [ 1.5 -2.  -8. ]
 [ 1.5  0.  -1. ]]


In [ ]:
A[1,:] = 1/2*A[1,:]
print(A)

[[ 1.  1.  3.]
 [ 0.  1.  4.]
 [ 0. -5.  5.]]


In [ ]:
X[1,:] = 1/2*X[1,:]
print(X)

[[ 0.5   0.    0.  ]
 [ 0.75 -1.   -4.  ]
 [ 1.5   0.   -1.  ]]


In [ ]:
A[2,:] = 5*A[1,:] + A[2,:]
print(A)

[[ 1.  1.  3.]
 [ 0.  1.  4.]
 [ 0.  0. 25.]]


In [ ]:
X[2,:] = 5*X[1,:] + X[2,:]
print(X)

[[  0.5    0.     0.  ]
 [  0.75  -1.    -4.  ]
 [  5.25  -5.   -21.  ]]


In [ ]:
A[0,:] = A[0,:] - A[1,:]
print(A)

[[ 1.  0. -1.]
 [ 0.  1.  4.]
 [ 0.  0. 25.]]


In [ ]:
X[0,:] = X[0,:] - X[1,:]
print(X)

[[ -0.25   1.     4.  ]
 [  0.75  -1.    -4.  ]
 [  5.25  -5.   -21.  ]]


In [ ]:
A[2,:] = 1/25*A[2,:]
print(A)

[[ 1.  0. -1.]
 [ 0.  1.  4.]
 [ 0.  0.  1.]]


In [ ]:
X[2,:] = 1/25*X[2,:]
print(X)

[[-0.25  1.    4.  ]
 [ 0.75 -1.   -4.  ]
 [ 0.21 -0.2  -0.84]]


In [ ]:
A[1,:] = -4*A[2,:] + A[1,:]
print(A)

[[ 1.  0. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [ ]:
X[1,:] = -4*X[2,:] + X[1,:]
print(X)

[[-0.25  1.    4.  ]
 [-0.09 -0.2  -0.64]
 [ 0.21 -0.2  -0.84]]


In [ ]:
A[0,:] = A[2,:] + A[0,:]
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
X[0,:] = X[2,:] + X[0,:]
print(X)

[[-0.04  0.8   3.16]
 [-0.09 -0.2  -0.64]
 [ 0.21 -0.2  -0.84]]


In [ ]:
U = X.dot(A)
print(U)

[[-0.04  0.8   3.16]
 [-0.09 -0.2  -0.64]
 [ 0.21 -0.2  -0.84]]


In [ ]:
L = np.matrix('2.0,2.0,6.0;3.0,1.0,1.0;3.0,8.0,4.0')
print(L)

[[2. 2. 6.]
 [3. 1. 1.]
 [3. 8. 4.]]


In [ ]:
U = L.dot(X)
print(U)

[[1.00000000e+00 1.11022302e-16 2.22044605e-16]
 [0.00000000e+00 2.00000000e+00 8.00000000e+00]
 [2.22044605e-16 6.66133815e-16 1.00000000e+00]]
