In [ ]:
import numpy as np

In [ ]:
A = np.matrix('3.0,7.0,9.0;2.0,4.0,8.0;4.0,9.0,7.0')
print(A)

[[3. 7. 9.]
 [2. 4. 8.]
 [4. 9. 7.]]


In [ ]:
B = np.identity(3)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
C = A.dot(B)
print(C)

[[3. 7. 9.]
 [2. 4. 8.]
 [4. 9. 7.]]


In [ ]:
D = B.dot(A)
print(D)

[[3. 7. 9.]
 [2. 4. 8.]
 [4. 9. 7.]]


In [ ]:
X = np.matrix('2.0,4.0;4.0,3.0;3.0,9.0')
print(X)

[[2. 4.]
 [4. 3.]
 [3. 9.]]


In [ ]:
E = B.dot(X)
print(E)

[[2. 4.]
 [4. 3.]
 [3. 9.]]


In [ ]:
Z = np.identity(4)
print(Z)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
W = np.matrix('1.0;2.0;4.0;6.0')
print(W)

[[1.]
 [2.]
 [4.]
 [6.]]
