In [ ]:
import numpy as np

In [ ]:
A = np.matrix('1.0, 1.0, 2.0, 9.0; 2.0, 4.0, -3.0, 1.0; 3.0, 6.0, -5.0, 0.0')

In [ ]:
print(A)

[[ 1.  1.  2.  9.]
 [ 2.  4. -3.  1.]
 [ 3.  6. -5.  0.]]


In [ ]:
A[1,:] = -2*A[0,:] + A[1,:]
print(A)

[[  1.   1.   2.   9.]
 [  0.   2.  -7. -17.]
 [  3.   6.  -5.   0.]]


In [ ]:
A[2,:] = A[2,:] - 3*A[0,:]

In [ ]:
print(A)

[[  1.   1.   2.   9.]
 [  0.   2.  -7. -17.]
 [  0.   3. -11. -27.]]


In [ ]:
A[1,:] = 1/2*A[1,:]
print(A)

[[  1.    1.    2.    9. ]
 [  0.    1.   -3.5  -8.5]
 [  0.    3.  -11.  -27. ]]


In [ ]:
A[2,:] = A[2,:] -3*A[1,:]
print(A)

[[ 1.   1.   2.   9. ]
 [ 0.   1.  -3.5 -8.5]
 [ 0.   0.  -0.5 -1.5]]


In [ ]:
A[1,:] = A[1,:] - 7*A[2,:]
print(A)

[[ 1.   1.   0.   3. ]
 [ 0.   1.   3.5 12.5]
 [ 0.   0.  -1.  -3. ]]
